language: php
php:
  - 7.3
  - 7.4
  - 8.0
services: memcached
install: composer install
before_script: yes '' | pecl install -f memcached
script:
  - ./vendor/bin/psalm
  - vendor/bin/phpunit tests
  - php benchmarks/MatryoshkaBenchmark.php
