language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
services: memcached
before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.5" ] || [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then phpenv config-add .travisphpconfig.ini ; echo no | pecl install -f apcu-5.1.11; fi;'
script:
  - phpunit tests
  - php benchmarks/MatryoshkaBenchmark.php
