name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.0"
          - "8.1"

        include:
          - os: ubuntu-latest
            php-version: "8.0"
            compiler: jit

          - os: ubuntu-latest
            php-version: "8.1"
            compiler: jit

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP with extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: memcached-3.2.0
        coverage: none
          env:
        fail-fast: true

    - name: Setup Memcached server
      uses: niden/actions-memcached@v7

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests with phpunit
      run: ./vendor/bin/phpunit tests

    - name: Static Analysis
      run: ./vendor/bin/psalm

    - name: Benchmarks
      run: php benchmarks/MatryoshkaBenchmark.php
